apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
{{ include "chatops-knight.labels" . | indent 4 }}
spec:
  type: {{ .Values.global.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.global.service.nodeport }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "chatops-knight.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
